on:
  push:
    branches:
      - test-release-it-1
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: dam-backend
          command: manifest
          targetBranch: test-release-it-1
          default-branch: test-release-it-1
