name: Sync Prod to Dev

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      matrix:
        node-version: ["14.x"]

    steps:
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client

    - name: Create user for dev
      run: |
        mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "CREATE USER 'dev'@'%' IDENTIFIED BY 'dev';"
        mysql --host 127.0.0.1 --port 32574 -uroot -ppassword -e "GRANT ALL PRIVILEGES ON * . * TO 'dev'@'%';"

    - name: Create test database
      run: |
        mysql_config_editor set --login-path=dev --user=dev --host=localhost --host=127.0.0.1 --port=32574 -p | echo dev
        mysql --login-path=dev  -e "SHOW DATABASES;"

      # - name: Connect to Dev DB
      #   run: ssh -fNT -o StrictHostKeyChecking=no -i ./moves.pem ec2-user@ec2-3-84-181-81.compute-1.amazonaws.com -L 5434:db.dev.my.vetmoves.com:5432

      # - name: Connect to Prod DB
      #   run: ssh -fNT -o StrictHostKeyChecking=no -i ./moves.pem ec2-user@ec2-3-84-181-81.compute-1.amazonaws.com -L 5437:db.my.vetmoves.com:5432

      # - name: Sync Prod DB to Dev DB
      #   run: pg_dump -Fc -O -x -h localhost -p 5437 -U $PROD_DB_USERNAME $PROD_DB_DATABASE --exclude-table-data 'cache*' --exclude-table-data 'password_resets' --exclude-table-data 'personal_access_tokens' --exclude-table-data 'sessions' --exclude-table-data 'telescope*' | pg_restore -O -x -c --if-exists -h localhost -p 5434 -U $DEV_DB_USERNAME -d $DEV_DB_DATABASE
      #   env:
      #     PGPASSFILE: .pgpass

      # - name: Seed Dev DB
      #   run: php artisan db:seed
